#!/bin/sh
#
###################################################################
# output format subroutines
#####################################
#
write_html_head() {
echo "Content-type: text/html"
echo ""
echo "<HTML><HEAD>"
echo "<TITLE>Plots for ${calid}</TITLE>"
echo "</HEAD><BODY>"
}
#
write_html_end() {
echo "<CENTER><A HREF=\"${return}\">"
echo "[Back to Previous Page]</A></CENTER>"
echo "<P>"
echo "</BODY></HTML>"
}
#
noplot_error_msg() {
  echo "No calibration data files found for ${calid}"
  echo "<BR>"
  echo "Files must be located in /home/yawl/data/calibration/cond/${calyear}"
  echo "<BR>"
}
#
usage_error_msg() {
  echo ""
  echo "Usage: plotcondcal calid [gmtoffset]"
  echo "<BR>"
  echo "   Must provide at lease one argument - calibration ID string (e.g. SB01144)"
  echo "<BR>"
}
#
###################################################################
#                   *** Execution starts here ***
###################################################################
#
# Set local variables from environment variables set by browser
###############################################################
calid=`echo $QUERY_STRING | sed -e 's/^.*calid=\(.*\)&gmtoff.*/\1/' | tr -cd '[:alnum:].' | tr '[A-Z]' '[a-z]'`
gmtoff=`echo $QUERY_STRING | sed -e 's/^.*gmtoff=\(.*\)$/\1/' | tr -cd '[:digit:]'`

return=`echo $HTTP_REFERER`
if [ "${return}" = "" ]; then
  return="http://yawl.pmel.noaa.gov/~taodata/calibrations.html"
fi
#
calyear="20`expr "${calid}" : '[a-z]*\([0-9][0-9]\)[0-9]*'`"
webroot="/rtplot"
unixroot="/var/www/htdocs/rtplot"
scriptdir="/home/yawl/taoproc/calcheck"
calibdir="/home/yawl/data/calibration/cond/${calyear}"
PLOTCAL="${scriptdir}/webplot_condcal"

#
######
#
# All Output starts here
########################
write_html_head
#
if [ -z "${calid}" ]; then
  usage_error_msg
#
else
  fileid=`echo ${calid} | cut -d"." -f1`
  if [ ! -f "${calibdir}/${fileid}.cal" ]; then
     noplot_error_msg
  else
     cd ${unixroot}
     rm -f ${fileid}*.png
     ${PLOTCAL} ${fileid} ${gmtoff}

     for plot in ${fileid}*.png
     do
        if [ -r "${plot}" ]; then
           echo "<IMG SRC=\"${webroot}/${plot}\">"
           echo "<HR>"
        fi
     done
  fi
fi
#
write_html_end
#
exit
